### ISSUE TITLE
error with gcc10

### ISSUE THREAD

**Issue by GengSS** [cp2k/libint-cp2k#3]
Dear Cp2k/libint developers,

It seems there is a bug with gcc10 in the source of old libint. 
https://github.com/evaleev/libint/issues/173

The bug has been fixed in the source code of libint, but not updated with the CP2K configured tarballs yet,
Please let me know if there is a workaround for it.

Thank you very much

Best,
Geng

**Comment by fxcoudert** [comment]
This is preventing cp2k from being updated in Homebrew: https://github.com/Homebrew/homebrew-core/pull/68951

**Comment by dev-zero** [comment]
As documented in the referenced issue evaleev/libint#173 this is not a bug in libint but a regression in gcc-10.1 and gcc-10.2. The patch I wrote was accepted for gcc-10.3 and trunk. Please update your compilers.

**Comment by dev-zero** [comment]
the respective gcc issue can be found here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95889

**Comment by fxcoudert** [comment]
> The patch I wrote was accepted for gcc-10.3 and trunk. Please update your compilers

I know, but gcc 10.3 is not released and will not be released for several months (nor GCC 11). Given that a workaround seems possible (later versions of libint don't have the issue), I was hoping this could be included.

**Comment by dev-zero** [comment]
Homebrew provides a compiler. A compiler with a regression. A regression which was fixed at upstream. You could fix that in Homebrew. Whether or not newer versions of libint give consistent results across all platforms was not verified and hence we don't support that. Since we have a rather large amount of dependencies by now to verify we can not support all pre-releases (and a beta is a pre-release) of any dependency.
